export const provincesData = [
  { name: 'Aceh', cities: ['Banda Aceh', 'Lhokseumawe', 'Langsa'] },
  { name: 'Sumatera Utara', cities: ['Medan', 'Binjai', 'Tebing Tinggi'] },
  { name: 'Sumatera Barat', cities: ['Padang', 'Bukittinggi', 'Solok'] },
  { name: 'Riau', cities: ['Pekanbaru', 'Dumai', 'Bengkalis'] },
  { name: 'Kepulauan Riau', cities: ['Tanjung Pinang', 'Batam', 'Bintan'] },
  { name: 'Jambi', cities: ['Jambi', 'Sungai Penuh', 'Muara Bungo'] },
  { name: 'Bengkulu', cities: ['Bengkulu', 'Rejang Lebong', 'Kepahiang'] },
  { name: 'Sumatera Selatan', cities: ['Palembang', 'Lubuklinggau', 'Prabumulih'] },
  { name: 'Lampung', cities: ['Bandar Lampung', 'Metro', 'Lampung Tengah'] },
  { name: 'DKI Jakarta', cities: ['Jakarta Pusat', 'Jakarta Barat', 'Jakarta Timur', 'Jakarta Selatan', 'Jakarta Utara'] },
  { name: 'Jawa Barat', cities: ['Bandung', 'Bekasi', 'Bogor', 'Depok', 'Cirebon'] },
  { name: 'Jawa Tengah', cities: ['Semarang', 'Surakarta', 'Magelang', 'Tegal', 'Purwokerto'] },
  { name: 'DI Yogyakarta', cities: ['Yogyakarta', 'Sleman', 'Bantul', 'Gunung Kidul', 'Kulon Progo'] },
  { name: 'Jawa Timur', cities: ['Surabaya', 'Malang', 'Kediri', 'Blitar', 'Jember'] },
  { name: 'Bali', cities: ['Denpasar', 'Singaraja', 'Tabanan'] },
  { name: 'Nusa Tenggara Barat', cities: ['Mataram', 'Bima', 'Sumbawa'] },
  { name: 'Nusa Tenggara Timur', cities: ['Kupang', 'Ende', 'Maumere'] },
  { name: 'Kalimantan Barat', cities: ['Pontianak', 'Singkawang', 'Ketapang'] },
  { name: 'Kalimantan Tengah', cities: ['Palangka Raya', 'Pangkalan Bun', 'Sampit'] },
  { name: 'Kalimantan Selatan', cities: ['Banjarmasin', 'Banjarbaru', 'Martapura'] },
  { name: 'Kalimantan Timur', cities: ['Samarinda', 'Balikpapan', 'Tenggarong'] },
  { name: 'Kalimantan Utara', cities: ['Tarakan', 'Tanjung Selor', 'Nunukan'] },
  { name: 'Sulawesi Utara', cities: ['Manado', 'Bitung', 'Tomohon'] },
  { name: 'Sulawesi Tengah', cities: ['Palu', 'Poso', 'Tolitoli'] },
  { name: 'Sulawesi Selatan', cities: ['Makassar', 'Parepare', 'Palopo'] },
  { name: 'Sulawesi Tenggara', cities: ['Kendari', 'Baubau', 'Kolaka'] },
  { name: 'Gorontalo', cities: ['Gorontalo', 'Marisa', 'Tilamuta'] },
  { name: 'Maluku', cities: ['Ambon', 'Masohi', 'Tual'] },
  { name: 'Maluku Utara', cities: ['Sofifi', 'Ternate', 'Tidore'] },
  { name: 'Papua', cities: ['Jayapura', 'Merauke', 'Wamena'] },
  { name: 'Papua Barat', cities: ['Manokwari', 'Sorong', 'Raja Ampat'] },
  // Tambahkan provinsi lainnya jika diperlukan
];
